---
- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone repository
  git:
    repo: "https://github.com/Sachin-960/nodejs_github_actions"
    dest: /home/ubuntu/myapp
    version: main

- name: Add NodeSource APT repository
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x  | sudo -E bash -

- name: Install Node.js and npm
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Verify Node and npm versions
  shell: |
    node -v
    npm -v

- name: Install app dependencies
  shell: |
    cd /home/ubuntu/myapp
    npm install

- name: Start application
  shell: |
    cd /home/ubuntu/myapp
    nohup npm start > app.log 2>&1 &