---
- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone repository
  git:
    repo: "https://github.com/Sachin-960/nodejs_github_actions"
    dest: /home/ubuntu/myapp
    version: main

- name: Remove old Node.js if exists (to avoid conflicts)
  apt:
    name: ["nodejs", "npm"]
    state: absent
    purge: yes

- name: Clean up any broken dependencies
  shell: sudo apt --fix-broken install -y

- name: Add NodeSource APT repository
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x  | sudo -E bash -

- name: Install Node.js (includes npm)
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Verify versions
  shell: |
    node -v
    npm -v

- name: Install app dependencies
  shell: |
    cd /home/ubuntu/myapp
    npm install

- name: Start application
  shell: |
    cd /home/ubuntu/myapp
    nohup npm start > app.log 2>&1 &