---
- name: Install git
  apt:
    name: git
    state: present

- name: Clone repository
  git:
    repo: "https://github.com/Sachin-960/nodejs_github_actions"
    dest: /home/ubuntu/myapp
    version: main

- name: Install Node.js and dependencies
  shell: |
    # Install NVM
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh  | bash

    # Load NVM in current shell
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    # Install and use Node.js 18
    nvm install 18
    node -v
    npm -v

- name: Install dependencies
  shell: |
    cd /home/ubuntu/myapp
    npm install

- name: Start application
  shell: |
    cd /home/ubuntu/myapp
    nohup node index.js > app.log 2>&1 &